---
-   name: Rusty Oven
    id: rusty_oven
    cost: 100
    prereq: []
    rating: 1
    type: oven
    junkyard: true

-   name: Electric Oven
    id: electric_oven
    cost: 100
    prereq: 
        - rusty_oven
    rating: 2
    type: oven

-   name: Rusty Fridge
    id: rusty_fridge
    cost: 500
    prereq: []
    rating: 1
    type: fridge
    junkyard: true

-   name: Rusty Fryer
    id: rusty_fryer
    cost: 100
    prereq: []
    rating: 1
    type: fryer
    junkyard: true

-   name: Rusty Griddle
    id: rusty_griddle
    cost: 100
    prereq: []
    rating: 1
    type: griddle
    junkyard: true
