---
- beef:
  name: Beef
  id: beef
  cost: 5
- chicken:
  name: Chicken
  id: chicken
  cost: 5
- turkey:
  name: Turkey
  id: turkey
  cost: 5
- eggs:
  name: Egg
  id: egg
  cost: 1
- pork:
  name: Pork
  id: pork
  cost: 5
- tomato:
  name: Tomato
  id: tomato
  cost: 1
- potato:
  name: Potato
  id: potato
  cost: 1
- bread:
  name: Bread
  id: bread
  cost: 2
- condiments:
  name: Mustard
  id: mustard
  cost: 1
- spices:
  name: Spices
  id: spices
  cost: 1
