---
- cubano:
    id: cubano
    tags:
        - sandwich
        - latino
    applianceNeeded:
        - plancha
        - oven
    ingredients:
        - bread
        - pork
        - mustard
- taco:
    id: taco
    tags:
        - mexican
        - latino
        - taco
    applianceNeeded: []
    ingredients: []
