---
dilapidated_truck:
    name: Dilapidated Food Truck
    id: dilapidated_truck
    appliance-slots: 3
    cost: 0
    # appliances: 
    #     - rusty_oven
    #     - rusty_fridge
    #     - rusty_griddle
    #     - rusty_fryer
    junkyard: true 

average_truck:
    name: Average Food Truck
    id: average_truck
    appliance-slots: 5
    cost: 500

amazing_truck: 
    name: Amazing Food Truck
    id: amazing_truck
    appliance-slots: 7
    cost: 1500
