---
dilapidated_truck:
    name: Dilapidated Food Truck
    id: dilapidated_truck
    appliance_slots: 3
    # TODO recipe  slots
    cost: 0
    # appliances: 
    #     - rusty_oven
    #     - rusty_fridge
    #     - rusty_griddle
    #     - rusty_fryer
    junkyard: true 

average_truck:
    name: Average Food Truck
    id: average_truck
    appliance_slots: 4
    cost: 500

amazing_truck: 
    name: Amazing Food Truck
    id: amazing_truck
    appliance_slots: 4
    cost: 1500
